variable "region" {
  description = "AWS region"
  type        = string
}

variable "cluster_name" {
  description = "Name of the Kubernetes cluster"
  type        = string
  default     = "polybot-cluster"
}

variable "vpc_id" {
  description = "ID of the VPC where resources will be created"
  type        = string
  default     = ""
}

variable "subnet_ids" {
  description = "List of subnet IDs for the Kubernetes cluster"
  type        = list(string)
  default     = []
}

variable "control_plane_instance_type" {
  description = "Instance type for the control plane node"
  type        = string
  default     = "t3.medium"
}

variable "worker_instance_type" {
  description = "Instance type for worker nodes"
  type        = string
  default     = "t3.medium"
}

variable "control_plane_ami" {
  description = "AMI ID for control plane node"
  type        = string
}

variable "worker_ami" {
  description = "AMI ID for worker nodes"
  type        = string
}

variable "route53_zone_id" {
  description = "Route53 zone ID for DNS records"
  type        = string
}

variable "domain_name" {
  description = "Domain name for the SSL certificate (e.g., guy-polybot-lg.devops-int-college.com)"
  type        = string
  # Required - no default value
}

variable "enable_https" {
  description = "Whether to enable HTTPS listener with SSL certificate"
  type        = bool
  default     = true
}

variable "redirect_http_to_https" {
  description = "Whether to redirect HTTP traffic to HTTPS"
  type        = bool
  default     = false
}

variable "addons" {
  description = "List of URLs to Kubernetes add-on manifests to apply"
  type        = list(string)
  default     = []
}

variable "rebuild_workers" {
  description = "Flag to trigger rebuild of worker nodes"
  type        = bool
  default     = false
}

variable "rebuild_control_plane" {
  description = "Flag to trigger rebuild of the control plane instance"
  type        = bool
  default     = false
}

variable "tags" {
  description = "A map of tags to add to all resources"
  type        = map(string)
  default     = {}
}

variable "ssh_public_key" {
  description = "The SSH public key content to be installed on instances"
  type        = string
  default     = ""
  sensitive   = true
}

variable "skip_api_verification" {
  description = "Skip API server verification (true/false)"
  type        = bool
  default     = false
}

variable "skip_token_verification" {
  description = "Skip join token verification (true/false)"
  type        = bool
  default     = false
}

variable "verification_max_attempts" {
  description = "Maximum number of attempts for control plane verification"
  type        = number
  default     = 20
}

variable "verification_wait_seconds" {
  description = "Seconds to wait between verification attempts"
  type        = number
  default     = 30
}

variable "pod_cidr" {
  description = "CIDR block for Kubernetes pod network"
  type        = string
  default     = "10.244.0.0/16"
}

variable "deployment_environment" {
  description = "Deployment environment (e.g., 'dev' or 'prod'). Used for naming resources and secrets."
  type        = string
  default     = "dev" 
  validation {
    condition     = contains(["dev", "prod"], var.deployment_environment)
    error_message = "Deployment environment must be 'dev' or 'prod'."
  }
}

variable "key_name" {
  description = "Name of an existing EC2 KeyPair in AWS to use for SSH access (e.g., 'polybot-aws-key'). If empty, a new key pair will be generated by Terraform."
  type        = string
  default     = ""
}

variable "ssh_private_key_file_path" {
  description = "Local path to the SSH private key file (e.g., '~/.ssh/polybot-key.pem'). Required if 'key_name' is specified and you want local-exec SSH to use it."
  type        = string
  default     = "" # You will set this to "~/.ssh/polybot-key.pem" when using your existing key
}

variable "desired_worker_nodes" {
  description = "Desired number of worker nodes for the Auto Scaling Group."
  type        = number
  default     = 2 # Or another appropriate default if you want one for the module
}

variable "force_cleanup_asg" {
  description = "If true, will delete the existing worker ASG before creating a new one. Use with caution - causes worker node replacement."
  type        = bool
  default     = false
}

variable "alb_health_check_path" {
  description = "The path for the ALB target group health check (e.g., /healthz, /)."
  type        = string
  default     = "/" # Or a more specific default like "/healthz"
}

variable "alb_ssl_policy" {
  description = "The SSL security policy for the ALB's HTTPS listener."
  type        = string
  default     = "ELBSecurityPolicy-TLS-1-2-Ext-2018-06" # A common secure default, adjust as needed
}

variable "control_plane_root_volume_size" {
  description = "The size of the root EBS volume for the control plane instance, in GiB."
  type        = number
  default     = 20 # Or another sensible default like 30 or 50
}

variable "worker_root_volume_size" {
  description = "The size of the root EBS volume for worker nodes, in GiB."
  type        = number
  default     = 20 # Or another sensible default like 30 or 50
}

variable "min_worker_nodes" {
  description = "Minimum number of worker nodes in the ASG."
  type        = number
  default     = 1 # Or your preferred default minimum
}

variable "max_worker_nodes" {
  description = "Maximum number of worker nodes in the ASG."
  type        = number
  default     = 3 # Or your preferred default maximum
}

variable "root_kubeconfig_path" {
  description = "The local file system path to the kubeconfig file generated by the root module, for use by local-exec scripts within this module."
  type        = string
  # No default is fine if it's always expected to be passed from the root module.
  # Add a default if the module might be used standalone or has a fallback.
}

variable "asg_scale_up_heartbeat_timeout" {
  description = "The heartbeat timeout in seconds for the ASG scale-up lifecycle hook."
  type        = number
  default     = 300 # Example: 5 minutes
}

variable "asg_scale_down_heartbeat_timeout" {
  description = "The heartbeat timeout in seconds for the ASG scale-down lifecycle hook."
  type        = number
  default     = 300 # Example: 5 minutes
}