apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-credentials
  namespace: prod
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "${DOCKER_USERNAME}",
          "password": "${DOCKER_PASSWORD}",
          "auth": "${BASE64_ENCODED_DOCKER_USERNAME_PASSWORD}"
        }
      }
    } 