apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-credentials
  namespace: prod
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "guymeltzer",
          "password": "Candy2025!",
          "auth": "Z3V5bWVsdHplcjpDYW5keTIwMjUh"
        }
      }
    } 