# PolybotInfra/mongodb/application.yaml
apiVersion: argoproj.io/v1alpha1  # Changed from argocd.argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd  # Added to ensure it’s created in the argocd namespace
spec:
  project: default  # Added for clarity, optional if default project is fine
  source:
    repoURL: https://github.com/guymeltzer/PolybotInfra.git
    path: k8s/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated: {}