# PolybotInfra/mongodb/application.yaml
apiVersion: argocd.argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
spec:
  source:
    repoURL: https://github.com/guymeltzer/PolybotInfra
    path: mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated: {}