apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  ubuntu@ip-10-0-0-17:~/k8s/mongodb$ cat replicaset.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
spec:
  template:
    spec:
      containers:
        - name: mongodb-init
          image: mongo:5
          command:
            - bash
            - -c
            - |
              until mongo --host mongodb-0.mongodb --eval "print('waiting for connection')"
              do
                sleep 2
              done
              mongo --host mongodb-0.mongodb --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongodb-0.mongodb:27017"}, {_id: 1, host: "mongodb-1.mongodb:27017"}, {_id: 2, host: "mongodb-2.mongodb:27017"}]})'
      restartPolicy: OnFailure