apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017  # You can specify any available port within the 30000-32767 range
  type: NodePort  # Change this to NodePort
  clusterIP: None
