apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp2
  encrypted: "true"
allowVolumeExpansion: true
