apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    chart: cluster-autoscaler
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.29.0
    helm:
      parameters:
        - name: autoDiscovery.clusterName
          value: polybot-cluster
        - name: awsRegion
          value: eu-north-1
        - name: cloud-provider
          value: aws
        - name: extraArgs.skip-nodes-with-local-storage
          value: "false"
        - name: extraArgs.expander
          value: least-waste
        - name: extraArgs.scale-down-utilization-threshold
          value: "0.5"
        - name: extraArgs.max-node-provision-time
          value: 15m
destination:
  server: https://kubernetes.default.svc
  namespace: kube-system
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true