apiVersion: v1
kind: Secret
metadata:
  name: polybot-secrets
  namespace: prod
type: Opaque
stringData:
  telegram_token: "${TELEGRAM_TOKEN}"
  sqs_queue_url: "${SQS_QUEUE_URL}"
  s3_bucket_name: "${S3_BUCKET_NAME}"
  telegram_app_url: "${TELEGRAM_APP_URL}"
  aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
  aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  mongo_collection: "${MONGO_COLLECTION}"
  mongo_db: "${MONGO_DB}"
  mongo_uri: "${MONGO_URI}"
  polybot_url: "${POLYBOT_URL}" 