apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-consumer
spec:
  replicas: 20
  selector:
    matchLabels:
      app: resource-consumer
  template:
    metadata:
      labels:
        app: resource-consumer
    spec:
      containers:
      - name: resource-consumer
        image: k8s.gcr.io/ubuntu-slim:0.1
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        command: ["sh", "-c", "while true; do sleep 10; done"]