apiVersion: v1
kind: Service
metadata:
  name: polybot-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 31024       # Service port exposed in the cluster
      targetPort: 31024 # Port on the pod
      protocol: TCP
  selector:
    app: polybot