apiVersion: v1
kind: Service
metadata:
  name: polybot-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 30619
      targetPort: 30619
      protocol: TCP
  selector:
    app: polybot