apiVersion: v1
kind: Service
metadata:
  name: polybot-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 30619       # Service port exposed in the cluster
      targetPort: 30619 # Port on the pod
      protocol: TCP
  selector:
    app: polybot