apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo5
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guymeltzer/PolybotInfra.git
    path: k8s/Yolo5
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 