apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      volumes:
        - name: polybot-certs
          secret:
            secretName: polybot-tls
        - name: polybot-ca
          secret:
            secretName: polybot-ca
      containers:
        - name: yolo5
          image: guymeltzer/yolo5:1.0.109
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          volumeMounts:
            - name: polybot-certs
              mountPath: "/app/certs"
              readOnly: true
            - name: polybot-ca
              mountPath: "/app/ca"
              readOnly: true