apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: yolo5
          image: guymeltzer/yolo5:1.0.44
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: S3_BUCKET_NAME
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: SQS_QUEUE_URL
            - name: MONGO_URI
              value: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017"
            - name: MONGO_DB
              value: "config"
            - name: MONGO_COLLECTION
              value: "image_collection"
            - name: POLYBOT_URL
              value: "http://polybot-service:30619/results"
            # AWS Secrets Manager will be used in the application code for AWS credentials
