apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: polybot-certs
          secret:
            secretName: polybot-tls
        - name: polybot-ca
          secret:
            secretName: polybot-ca
      containers:
        - name: yolo5
          image: guymeltzer/yolo5:1.0.94
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: polybot-certs
              mountPath: "/app/certs"
              readOnly: true
            - name: polybot-ca
              mountPath: "/app/ca"
              readOnly: true
          env:
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: polybot-secrets
                  key: S3_BUCKET_NAME
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: polybot-secrets
                  key: SQS_QUEUE_URL
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: polybot-secrets
                  key: MONGO_URI
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: polybot-secrets
                  key: MONGO_DB
            - name: MONGO_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: polybot-secrets
                  key: MONGO_COLLECTION
            - name: POLYBOT_URL
              valueFrom:
                secretKeyRef:
                  name: polybot-secrets
                  key: POLYBOT_URL
            - name: TELEGRAM_APP_URL
              valueFrom:
                secretKeyRef:
                  name: polybot-secrets
                  key: TELEGRAM_APP_URL
